<aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="<?php echo BASE_IMG ?>usuarioh.jpg" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
              <p><?php echo session::get('nombre').' '.session::get('apellido') ?></p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <!--<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..." />
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form> -->
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
         
          <?php if(isset($_layoutParams))
                {
                	$menu = $_layoutParams['lista_menu'];
                  for($i = 0; $i < count($menu);$i++)
                  {
          ?>
          			<?php      
							if($_layoutParams['item'] && $menu[$i]['id'] == $_layoutParams['item'] )
			                { 
			                   	$_item_style = 'active'; 
			                } else {
			                    $_item_style = '';
			                }
							
					?>
                    <li class="treeview <?php echo $_item_style; ?>">
                      <a href="#">
                        <i class="<?php echo $_layoutParams['lista_menu'][$i]['imagen']  ?>"></i> <span><?php echo $_layoutParams['lista_menu'][$i]['titulo'] ?></span> <i class="fa fa-angle-left pull-right"></i>
                      </a>
                <?php if(isset($_layoutParams['lista_menu'][$i]['submenu']) && count($_layoutParams['lista_menu'][$i]['submenu'])): ?>        
                      <ul class="treeview-menu">
                    <?php foreach($_layoutParams['lista_menu'][$i]['submenu'] as $recurso): ?>  
                    	
                		<?php      
							if($_layoutParams['mod'] && $recurso['id'] == $_layoutParams['mod'] )
			                { 
			                   	$_item_style = 'active'; 
			                } else {
			                    $_item_style = '';
			                }
							
						?>
                    	    
                          <li class="<?php echo $_item_style; ?>" ><a  href="<?php echo $recurso['enlace'] ?>"><i class="<?php echo $recurso['imagen']  ?>"></i><?php echo ucfirst($recurso['titulo']) ?></a></li>          
                    <?php endforeach; ?>  
                      </ul>
                <?php endif; ?>        
                    </li>
          <?php
                  }
                }
          ?>
                        
        </section>
        <!-- /.sidebar -->
      </aside>